### ISSUE TITLE
debouncer issue?

### ISSUE THREAD

**Issue by clangaxon** [petems/petems-hiera_vault#14]
I see this was literally added yesterday. :)

Just installing vault:

Must install debouncer gem to use hiera-vault backend

so I:

puppetserver gem install debouncer (gets 0.2.2):

Internal Server Error: org.jruby.exceptions.RaiseException: (SyntaxError) /opt/puppetlabs/server/data/puppetserver/jruby-gems/gems/debouncer-0.2.2/lib/debouncer.rb:86: syntax error, unexpected tLABEL
  def flush(id = EMPTY, and_join: false)

Dropping to debouncer 0.1.0:

Evaluation Error: Error while evaluating a Function Call, Function Load Error for function 'hiera_vault': undefined method `shutdown' for #<Vault::Client:0x180f2b89>

Not sure if this is a WIP, I'm doing something wrong, or ? :)

Thanks!

**Comment by othalla** [comment]
Getting the same issue

**Comment by cqwense** [comment]
I believe the debouncer 0.2.2 problem is realted to which version of puppetserver you're using - mine is still bundled with ruby 1.9 and I get the same error.

dropping down to 0.1.0 will work, if you do one of two things:

1) point your puppetfile's reference to this module to commit SHA 
7bf6219b3afbcb4da8d21ad160bb546eb058cdf6

which is the commit before the call to the vault gem's shutdown function was added.

2) you can build your own version of the vault gem from https://github.com/hashicorp/vault-ruby/commit/5e5688a0947c1c60464b7b17ff59bb623c4085ea ( or later ) since that commit/function hasn't made it into an official release yet.

**Comment by clangaxon** [comment]
fwiw, we got around this by switching Puppet to JRuby 9k.

**Comment by petems** [comment]
Yep, the solution is either: Upgrade to Puppetserver 6 where JRuby has been changed to JRUBY9K by default, or change it.

Here's some example code:

```
  ini_setting { "Change jruby to 9k":
    ensure  => present,
    setting => 'JRUBY_JAR',
    path    => "/etc/sysconfig/puppetserver",
    key_val_separator => '=',
    section => '',
    value   => '"/opt/puppetlabs/server/apps/puppetserver/jruby-9k.jar"',
    show_diff => true,
    notify  => Class['puppetserver::service']
  }
  ->
  package { 'vault-puppetserver-gem':
    ensure   => 'present',
    name     => 'vault',
    provider => 'puppetserver_gem',
  }
  ->
  package { 'vault-puppetpath-gem':
    ensure   => 'present',
    name     => 'vault',
    provider => 'puppet_gem',
  }
```

**Comment by petems** [comment]
Note added to Readme (8b54fbe735d6bb9862c2f2eca6853e84b3518947)
